//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SpeakerCancel {
            get {
                return ResourceManager.GetString("SpeakerCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string SpeakerCity {
            get {
                return ResourceManager.GetString("SpeakerCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Pres Email Address.
        /// </summary>
        internal static string SpeakerCoPresEmailAddress {
            get {
                return ResourceManager.GetString("SpeakerCoPresEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Presenters.
        /// </summary>
        internal static string SpeakerCoPresenters {
            get {
                return ResourceManager.GetString("SpeakerCoPresenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string SpeakerEmailAddress {
            get {
                return ResourceManager.GetString("SpeakerEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string SpeakerInsert {
            get {
                return ResourceManager.GetString("SpeakerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string SpeakerJobTitle {
            get {
                return ResourceManager.GetString("SpeakerJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Name.
        /// </summary>
        internal static string SpeakerName {
            get {
                return ResourceManager.GetString("SpeakerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string SpeakerOffice {
            get {
                return ResourceManager.GetString("SpeakerOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Description.
        /// </summary>
        internal static string SpeakerSessionDescription {
            get {
                return ResourceManager.GetString("SpeakerSessionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Number.
        /// </summary>
        internal static string SpeakerSessionNumber {
            get {
                return ResourceManager.GetString("SpeakerSessionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Title.
        /// </summary>
        internal static string SpeakerSessionTitle {
            get {
                return ResourceManager.GetString("SpeakerSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SpeakerUpdate {
            get {
                return ResourceManager.GetString("SpeakerUpdate", resourceCulture);
            }
        }
    }
}
